from flask_restplus import fields
GameModel = {
	'Games': fields.String,
	'Umpire': fields.String,
	'timeStamp': fields.Integer
}
UmpireModel = {   
        'All-star game': fields.Float,
        'B.S (Y/N)': fields.Float,
        'Children': fields.Float,
        'Data source': fields.String,
        'Division Series': fields.Float,
        'League Championship Series': fields.Float,
        'M.S (Y/N)': fields.Float,
        'Marital Status (Y/N)': fields.Float,
        'Other Leagues': fields.Float,
        'Umpire School/Camp Instructor (Y/N)': fields.Float,
        'Umpire School/Camp Student (Y/N)': fields.Float,
        'Wild Card Game': fields.Float,
        'World Series': fields.Float,
        'bad_call': fields.Float,
        'bad_call_ratio': fields.Float,
        'bc_ball': fields.Float,
        'bc_ball_ratio': fields.Float,
        'bc_strike': fields.Float,
        'bc_strike_ratio': fields.Float,
        'bcr_': fields.Float,
        'bcr_CH': fields.Float,
        'bcr_CU': fields.Float,
        'bcr_EP': fields.Float,
        'bcr_FC': fields.Float,
        'bcr_FF': fields.Float,
        'bcr_FS': fields.Float,
        'bcr_FT': fields.Float,
        'bcr_KC': fields.Float,
        'bcr_KN': fields.Float,
        'bcr_OT': fields.Float,
        'bcr_SI': fields.Float,
        'bcr_SL': fields.Float,
        'bcr_i1': fields.Float,
        'bcr_i2': fields.Float,
        'bcr_i3': fields.Float,
        'bcr_i4': fields.Float,
        'bcr_i5': fields.Float,
        'bcr_i6': fields.Float,
        'bcr_i7': fields.Float,
        'bcr_i8': fields.Float,
        'bcr_i9': fields.Float,
        'bcr_z1': fields.Float,
        'bcr_z11': fields.Float,
        'bcr_z12': fields.Float,
        'bcr_z13': fields.Float,
        'bcr_z14': fields.Float,
        'bcr_z2': fields.Float,
        'bcr_z3': fields.Float,
        'bcr_z4': fields.Float,
        'bcr_z5': fields.Float,
        'bcr_z6': fields.Float,
        'bcr_z7': fields.Float,
        'bcr_z8': fields.Float,
        'bcr_z9': fields.Float,
        'birth year': fields.Float,
        'call_ball': fields.Float,
        'call_strike': fields.Float,
        'number': fields.Float,
        'serve year': fields.Float,
        'total_call': fields.Float,
        'ump': fields.String
    }
