from flask_restplus import fields
PitcherObject = {
    'name': fields.String,
    'season': fields.Integer,
    'total_call': fields.Float,
    'BCR': fields.Float,
    'BCR_SL': fields.Float,
    'BCR_FT': fields.Float,
    'BCR_CU': fields.Float,
    'BCR_FF': fields.Float,
    'BCR_SI': fields.Float,
    'BCR_CH': fields.Float,
    'BCR_FC': fields.Float,
    'BCR_EP': fields.Float,
    'BCR_KC': fields.Float,
    'BCR_FS': fields.Float,
    # 'BCR_PO': fields.Float,
    'BCR_KN': fields.Float,
    # 'BCR_SC': fields.Float,
    'BCR_FO': fields.Float,
    # 'BCR_UN': fields.Float,
    # 'BCR_FA': fields.Float,
    # 'BCR_IN': fields.Float,
    'call_ball': fields.Float,
    'call_strike': fields.Float,
    'BCR': fields.Float,
    'blindspot_pitch': fields.Float
}
SearchObject = {
    'ump_profile_pic': fields.String,
    'name': fields.String,
    'data_year': fields.Integer
}
TeamObject = {
    'team': fields.String,
    'season': fields.Integer,
    'gamesUmped': fields.Integer,
    'pitchesCalled': fields.Integer,
    'ballsCalled': fields.Integer,
    'strikesCalled': fields.Integer,
    'icr': fields.Float,
    'seasonChangeIcr': fields.Float
}
UmpireGameObject = {
    'home': fields.String,
    'away': fields.String,
    'date': fields.String,
    # 'pitchesCalled': fields.Float,
    'icr': fields.Float,
    'teamPref': fields.String,
    'icrSL': fields.Float,
    'icrFT': fields.Float,
    'icrCU': fields.Float,
    'icrFF': fields.Float,
    'icrSI': fields.Float,
    'icrCH': fields.Float,
    'icrFC': fields.Float,
    'icrEP': fields.Float,
    'icrKC': fields.Float,
    'icrFS': fields.Float,
    # 'icrPO': fields.Float,
    'icrKN': fields.Float,
    # 'icrSC': fields.Float,
    'icrFO': fields.Float,
    # 'icrUN': fields.Float,
    # 'icrFA': fields.Float,
    'icrIN': fields.Float,
    'ballsCalled': fields.Float,
    'strikesCalled': fields.Float
    # 'consistency': fields.Float,
    # 'walksPerInning': fields.Float,
    # 'strikeoutsPerInning': fields.Float,
    # 'walksToStrikeoutsRatio'
}
CareerObject = {
    # 'season': fields.Integer,
    'status': fields.String,
    'gamesUmped': fields.Integer,
    'pitchesCalled': fields.Integer,
    'icr': fields.Float,
    # 'seasonChangeIcr': fields.Float,
    # 'bestPitch':
    # 'worstPitch':
    'icrSL':fields.Float,
    'icrFT':fields.Float,
    'icrCU':fields.Float,
    'icrFF':fields.Float,
    'icrSI':fields.Float,
    'icrCH':fields.Float,
    'icrFC':fields.Float,
    'icrEP':fields.Float,
    'icrKC':fields.Float,
    'icrFS':fields.Float,
    'icrPO':fields.Float,
    'icrKN':fields.Float,
    'icrSC':fields.Float,
    'icrFO':fields.Float,
    'icrUN':fields.Float,
    'icrFA':fields.Float,
    'icrIN':fields.Float
    # 'careerBestIcr':
    # 'paceOfPlay':
    # 'crucialBadCalls':
}
RankingsObjects = {
    'season': fields.Integer,
    'name': fields.String,
    # 'number': fields.Integer,
    # 'age': fields.Integer,
    'gamesUmped': fields.Integer,
    'pitchesCalled': fields.Integer,
    'icr': fields.Float
    # 'mostAccurateTeam': fields.String,
    # 'leastAccurateTeam': fields.String
}
GameDatePair = {
    'game': fields.Integer,
    'date': fields.String 
}
GameModel = {
	'Games': fields.String,
	'Umpire': fields.String,
	'timeStamp': fields.Integer
}
UmpireIDPair = {
    'name': fields.String,
    'id': fields.Integer,
    'ump_profile_pic': fields.String
}
UmpireObject = {
    'id':fields.Integer,
    'season': fields.Integer,
    'firstName': fields.String,
    'lastName': fields.String,
    # 'number': fields.Integer,
    'icr': fields.Float,
    # 'nickname': fields.String,
    'crewNumber': fields.String,
    'status': fields.String,
    'isCrewChief': fields.Integer,
    # 'consistency':
    # 'age':
    # 'yearsActive':
    # 'bias':
    # 'ranking':
    # 'favoriteTeam':
    # 'yearlyEjections':
    # 'bestMonth':
    # 'worstMonth':
    # 'bestSeason':
    # 'timePref':
    # 'favoritePark':
    # 'worstPark':
    # 'weatherPreference':
    'pitchesCalled': fields.Integer,
    'gamesUmped': fields.Integer
    # 'mostAccurateTeam':
    # 'leastAccurateTeam':
    # 'birthplace':
}
GameModel = {
    'BCR_in_8': fields.Float,
    'BCS_ratio_in_2': fields.Float,
    'BCR_in_7': fields.Float,
    'BCS_ratio_in_3': fields.Float,
    'BCR_in_9': fields.Float,
    'BCR_SC': fields.Float,
    'BCS_ratio_in_1': fields.Float,
    'BCR_in_4': fields.Float,
    'BCS_ratio_in_6': fields.Float,
    'BCR_in_3': fields.Float,
    'BCS_ratio_in_7': fields.Float,
    'bad_call_right': fields.Float,
    'BCR_in_6': fields.Float,
    'BCS_ratio_in_4': fields.Float,
    'BCR_in_5': fields.Float,
    'BCS_ratio_in_5': fields.Float,
    'bad_call_CU': fields.Float,
    'BCR_in_2': fields.Float,
    'total_call_EP': fields.Float,
    'BCR_in_1': fields.Float,
    'call_strike': fields.Float,
    'date': fields.String,
    'bad_call_ratio': fields.Float,
    'bad_call_KN': fields.Float,
    'strike_called_ball_in_10': fields.Float,
    'bad_call_CH': fields.Float,
    'BCS_ratio_in_10': fields.Float,
    'awayteam_y': fields.Float,
    'awayteam_x': fields.Float,
    'call_ball_in_1': fields.Float,
    'call_ball_in_2': fields.Float,
    'BCR_CH': fields.Float,
    'ump_x': fields.Float,
    'total_call_FS': fields.Float,
    'bcd_call_in_10': fields.Float,
    'call_ball_in_3': fields.Float,
    'ump_y': fields.Float,
    'total_call_FT': fields.Float,
    'call_ball_in_4': fields.Float,
    'call_ball_in_5': fields.Float,
    'call_ball_in_6': fields.Float,
    'call_ball_in_7': fields.Float,
    'BCR_KN': fields.Float,
    'call_ball_in_8': fields.Float,
    'call_ball_in_9': fields.Float,
    'bad_call_UN': fields.Float,
    'BCR_SL': fields.Float,
    'total_call_FO': fields.Float,
    'total_call_right': fields.Float,
    'total_call_': fields.Float,
    'total_call_FC': fields.Float,
    'BCR_SI': fields.Float,
    'BCR_KC': fields.Float,
    'SCB_ratio_in_10': fields.Float,
    'total_call_FF': fields.Float,
    'strike_called_ball': fields.Float,
    'bad_call_EP': fields.Float,
    'ump_x.1': fields.Float,
    'total_call_in_1': fields.Float,
    'total_call_in_2': fields.Float,
    'total_call_in_3': fields.Float,
    'total_call_in_4': fields.Float,
    'total_call_CU': fields.Float,
    'game': fields.Float,
    'awayteam': fields.Float,
    'total_call_CH': fields.Float,
    'SCB_ratio_in_1': fields.Float,
    'total_call_KN': fields.Float,
    'SCB_ratio_in_2': fields.Float,
    'total_call_in_10': fields.Float,
    'SCB_ratio_in_3': fields.Float,
    'SCB_ratio_in_4': fields.Float,
    'SCB_ratio_in_5': fields.Float,
    'SCB_ratio_in_6': fields.Float,
    'SCB_ratio_in_7': fields.Float,
    'call_ball_in_10': fields.Float,
    'data_year_y': fields.Float,
    'bad_call_': fields.Float,
    'data_year_x': fields.Float,
    'ball_called_strike_in_8': fields.Float,
    'ball_called_strike_in_9': fields.Float,
    'bad_call_FS': fields.Float,
    'bad_call_FT': fields.Float,
    'total_call_UN': fields.Float,
    'ball_called_strike_in_1': fields.Float,
    'ball_called_strike_in_2': fields.Float,
    'ball_called_strike_in_3': fields.Float,
    'ball_called_strike_in_4': fields.Float,
    'ball_called_strike_in_5': fields.Float,
    'ball_called_strike_in_6': fields.Float,
    'ball_called_strike_in_7': fields.Float,
    'bcd_call_in_7': fields.Float,
    'bcd_call_in_6': fields.Float,
    'bcd_call_in_9': fields.Float,
    'bad_call_FC': fields.Float,
    'bcd_call_in_8': fields.Float,
    'call_strike_in_3': fields.Float,
    'call_strike_in_4': fields.Float,
    'bad_call_FF': fields.Float,
    'call_strike_in_1': fields.Float,
    'call_strike_in_2': fields.Float,
    'call_strike_in_7': fields.Float,
    'call_strike_in_8': fields.Float,
    'call_strike_in_5': fields.Float,
    'BCS_ratio_in_8': fields.Float,
    'BCS_ratio_in_9': fields.Float,
    'call_strike_in_6': fields.Float,
    'preference': fields.Float,
    'call_strike_in_9': fields.Float,
    'bad_call_FO': fields.Float,
    'BCR_FS': fields.Float,
    'BCR_FT': fields.Float,
    'BCR_right': fields.Float,
    'BCR_FO': fields.Float,
    'ump_y.1': fields.Float,
    'worst_inning': fields.Float,
    'bad_call_home': fields.Float,
    'bcd_call_in_1': fields.Float,
    'call_strike_in_10': fields.Float,
    'bcd_call_in_3': fields.Float,
    'bcd_call_in_2': fields.Float,
    'bcd_call_in_5': fields.Float,
    'bcd_call_in_4': fields.Float,
    'BCR_FC': fields.Float,
    'BCR_FF': fields.Float,
    'bad_call': fields.Float,
    'bad_call_away': fields.Float,
    'total_call_SI': fields.Float,
    'bad_call_left': fields.Float,
    'total_call_SL': fields.Float,
    'total_call_KC': fields.Float,
    'SCB_ratio_in_8': fields.Float,
    'SCB_ratio_in_9': fields.Float,
    'total_call_SC': fields.Float,
    'best_inning': fields.Float,
    'total_call_in_9': fields.Float,
    'total_call_in_5': fields.Float,
    'total_call_in_6': fields.Float,
    'total_call_in_7': fields.Float,
    'total_call_in_8': fields.Float,
    'call_ball': fields.Float,
    'BCR_left': fields.Float,
    'BCR_in_10': fields.Float,
    'hometeam_y': fields.Float,
    'hometeam_x': fields.Float,
    'data_year_x.1': fields.Float,
    'ball_called_strike': fields.Float,
    'BCR_home': fields.Float,
    'BCR_away': fields.Float,
    'total_call_left': fields.Float,
    'id': fields.Float,
    'BCR_CU': fields.Float,
    'BCR_': fields.Float,
    'total_call_away': fields.Float,
    'hometeam': fields.Float,
    'BCR_EP': fields.Float,
    'bad_call_SC': fields.Float,
    'ball_called_strike_in_10': fields.Float,
    'total_call': fields.Float,
    'bad_call_SI': fields.Float,
    'strike_called_ball_ratio': fields.Float,
    'bad_call_KC': fields.Float,
    'bad_call_SL': fields.Float,
    'total_call_home': fields.Float,
    'BCR_UN': fields.Float,
    'strike_called_ball_in_8': fields.Float,
    'strike_called_ball_in_9': fields.Float,
    'strike_called_ball_in_4': fields.Float,
    'strike_called_ball_in_5': fields.Float,
    'strike_called_ball_in_6': fields.Float,
    'strike_called_ball_in_7': fields.Float,
    'ball_called_strike_ratio': fields.Float,
    'strike_called_ball_in_1': fields.Float,
    'data_year_y.1': fields.Float,
    'strike_called_ball_in_2': fields.Float,
    'strike_called_ball_in_3': fields.Float,
}
